### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by mv-dk** [amouat/revealjs-docker#5]
After running docker-compose up -d, the service starts and then shuts down. Doing docker-compose logs reveals the following:

```
revealjs_1  | /usr/local/lib/node_modules/grunt-cli/node_modules/micromatch/index.js:44
revealjs_1  |     let isMatch = picomatch(String(patterns[i]), { ...options, onResult }, true);
revealjs_1  |                                                    ^^^
revealjs_1  |
revealjs_1  | SyntaxError: Unexpected token ...
revealjs_1  |     at createScript (vm.js:56:10)
revealjs_1  |     at Object.runInThisContext (vm.js:97:10)
revealjs_1  |     at Module._compile (module.js:549:28)
revealjs_1  |     at Object.Module._extensions..js (module.js:586:10)
revealjs_1  |     at Module.load (module.js:494:32)
revealjs_1  |     at tryModuleLoad (module.js:453:12)
revealjs_1  |     at Function.Module._load (module.js:445:3)
revealjs_1  |     at Module.require (module.js:504:17)
revealjs_1  |     at require (internal/module.js:20:19)
revealjs_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/node_modules/findup-sync/index.js:12:10)
revealjs_1  | /usr/local/lib/node_modules/grunt-cli/node_modules/micromatch/index.js:44
revealjs_1  |     let isMatch = picomatch(String(patterns[i]), { ...options, onResult }, true);
revealjs_1  |                                                    ^^^
revealjs_1  |
revealjs_1  | SyntaxError: Unexpected token ...
revealjs_1  |     at createScript (vm.js:56:10)
revealjs_1  |     at Object.runInThisContext (vm.js:97:10)
revealjs_1  |     at Module._compile (module.js:549:28)
revealjs_1  |     at Object.Module._extensions..js (module.js:586:10)
revealjs_1  |     at Module.load (module.js:494:32)
revealjs_1  |     at tryModuleLoad (module.js:453:12)
revealjs_1  |     at Function.Module._load (module.js:445:3)
revealjs_1  |     at Module.require (module.js:504:17)
revealjs_1  |     at require (internal/module.js:20:19)
revealjs_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/node_modules/findup-sync/index.js:12:10)
revealjs_1  | /usr/local/lib/node_modules/grunt-cli/node_modules/micromatch/index.js:44
revealjs_1  |     let isMatch = picomatch(String(patterns[i]), { ...options, onResult }, true);
revealjs_1  |                                                    ^^^
revealjs_1  |
revealjs_1  | SyntaxError: Unexpected token ...
revealjs_1  |     at createScript (vm.js:56:10)
revealjs_1  |     at Object.runInThisContext (vm.js:97:10)
revealjs_1  |     at Module._compile (module.js:549:28)
revealjs_1  |     at Object.Module._extensions..js (module.js:586:10)
revealjs_1  |     at Module.load (module.js:494:32)
revealjs_1  |     at tryModuleLoad (module.js:453:12)
revealjs_1  |     at Function.Module._load (module.js:445:3)
revealjs_1  |     at Module.require (module.js:504:17)
revealjs_1  |     at require (internal/module.js:20:19)
revealjs_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/node_modules/findup-sync/index.js:12:10)
```

**Comment by amouat** [comment]
This is ancient Martin! It all needs updated I think. I don't use it any more, I guess I should put a warning on the repo :)
